powsybl/powsybl-single-line-diagram-server

- .gitignore
- checkstyle.xml
- pom.xml
- single-line-diagram-model/pom.xml
- single-line-diagram-model/src/main/java/com/powsybl/single/line/diagram/model/SingleLineDiagramApi.java
- single-line-diagram-server/pom.xml
- single-line-diagram-server/src/main/java/com/powsybl/single/line/diagram/server/SingleLineDiagramApplication.java
- single-line-diagram-server/src/main/java/com/powsybl/single/line/diagram/server/SingleLineDiagramController.java
- single-line-diagram-server/src/main/java/com/powsybl/single/line/diagram/server/SingleLineDiagramService.java
- single-line-diagram-server/src/main/java/com/powsybl/single/line/diagram/server/SingleLineDiagramSwaggerConfig.java
- single-line-diagram-server/src/main/resources/application.yml
- single-line-diagram-server/src/test/java/com/powsybl/single/line/diagram/server/SingleLineDiagramTest.java
> Initial commit

- pom.xml
- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
No
Bug fix
Code coverage is not correct on SonarCloud
Jacoco is now correctly configured to feed SonarCloud
**Other …
> Fix code coverage

- pom.xml
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>
#7
> upgrade to single-line-diagram 1.1.0

- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>
> Add useName param

- .github/workflows/maven.yml
- pom.xml
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
No
feature
Single line diagram dependency is 1.2.0 
Single line diagram dependency is 1.3.0-SNAPSHOT
> Change single line diagram dependency to 1.3.0-SNAPSHOT 

- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
No
Bug fix
Code does not compile anymore due to single line diagram core changes
Code compile again 
(if …
> Adapt to single line diagram changes

- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
No
feature
An option has been added to use topological style provider instead of nominal voltage style provider.
(if any of the questions/checkboxes don't apply, please delete them …
> Topological coloring

- pom.xml
> Migrate to PowSyBl Core 3.2.0

- pom.xml
No
Bug fix
powsybl-single-line-diagram master is 1.6.0-SNAPSHOT
> Use Single Line Diagram 1.6.0-SNAPSHOT

- pom.xml
No
Bug fix
compilation is broken
single line diagram dependency has to be changed to 1.7.0-SNAPSHOT
(if …
> Use single line diagram 1.7.0-SNAPSHOT

- .github/workflows/maven.yml
- pom.xml
> Use single line diagram release

- .github/workflows/maven.yml
> Remove single line diagram build notification as we now use release

- pom.xml
- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
https://github.com/gridsuite/study-server/pull/52
> Add diagram for substations

- pom.xml
- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>
feature
powsybl 3.8.0 and SLD 1.8.0
powsybl 4.0.1 and SLD 2.0.0
> powsybl 4.0.1 + sld 2.0.0

- pom.xml
Signed-off-by: Jon Harper <jon.harper87@gmail.com>
NO
BugFix
the image contains powsybl 4.0.0 and powysbl 4.0.1 jars
only 4.0.1 jars
NO
> Cleanup dependencies

- pom.xml
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
Signed-off-by: HARPER Jon <jon.harper87@gmail.com>
NO
feature
powsybl 4.2.0, sld 2.2.0
powysbl 4.3.1, sld 2.3.0
NO
> Upgrade to powsybl 4.3.1

- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
Bug fix
Useless external imports of css are generated in svg file with '@import url' directives
No external imports of css are generated in svg file (they are provided by the study-app front application)
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the …
> No css import in svg generated files

- pom.xml
- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramSwaggerConfig.java
- src/main/resources/application.yml
Replacing springfox with springdoc
> Replace springfox with springdoc

- pom.xml
- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
- src/main/java/com/powsybl/sld/utils/DiagramParameters.java
No
Feature
PowSyBl Core 4.5.1 is used
PowSyBl Core 4.6.1 is used
(if any of the questions/checkboxes …
> Migrate to PowSyBl 4.6.1

- pom.xml
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
- src/main/resources/GridSuiteLibrary/components.json
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
No
feature
PowSyBl 4.6.1
PowSyBl 4.7.0
> Migrate to PowSyBl 4.7.0

- pom.xml
Signed-off-by: Seddik Yengui <seddik.yengui@rte-france.com>
> Spring boot 2.6.6 migration

- pom.xml
- src/main/resources/GridSuiteLibrary/components.json
Signed-off-by: HARPER Jon <jon.harper87@gmail.com>
NO
bugfix
powsybl-single-line-diagram.version 2.9.1
powsybl-single-line-diagram.version 2.10.0
NO
> fixup powsybl110, single-line-diagram should be 2.10

- pom.xml
- src/main/java/com/powsybl/sld/server/NetworkAreaDiagramService.java
> Upgrade to PowSyBl 2022.0.0

- src/main/resources/application-local.yml
Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>
> homogenize of backing services keys

- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
Signed-off-by: TOURI ANIS <anis-1.touri@rte-france.com>
> Homogenize NAD/SLD returns

- .github/workflows/maven.yml
- pom.xml
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
> Migrate to PowSyBl WS 2.1.0

- pom.xml
- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
- src/main/java/com/powsybl/sld/server/utils/SingleLineDiagramParameters.java
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
Update to powsybl-parent-ws 10
> Upgrade to powsybl-parent-ws 10

- src/main/java/com/powsybl/sld/server/NetworkAreaDiagramService.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
- src/main/java/com/powsybl/sld/server/dto/EquipmentInfos.java
- src/main/java/com/powsybl/sld/server/dto/SubstationInfos.java
- src/main/java/com/powsybl/sld/server/dto/SvgAndMetadata.java
- src/main/java/com/powsybl/sld/server/dto/VoltageLevelInfos.java
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
> Return some additional metadata with the SVG

- pom.xml
NO
feature
no <relativePath/> for parent. Maven might show a warning when another pom is placed above this project.
<relativePath/> like in all other projects
NO
> pom.xml: add <relativePath/> like in our other projects

- pom.xml
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
> springboot 3.1.2

- pom.xml
- src/main/java/com/powsybl/sld/server/NetworkAreaDiagramService.java
- src/main/java/com/powsybl/sld/server/PositionDiagramLabelProvider.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
> powsybl ws dependencies 2.5.0

- pom.xml
- src/main/java/com/powsybl/sld/server/SingleLineDiagramApplication.java
> update to powsybl-ws-dependencies 2.6.0

- src/main/java/com/powsybl/sld/server/dto/SubstationInfos.java
- src/main/java/com/powsybl/sld/server/dto/VoltageLevelInfos.java
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
> Homogenize substation attributes

- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
> Fix sonar failure

- pom.xml
> upgrade network store server to v1.16.0

- pom.xml
> upgrade network store to v1.17.1

- pom.xml
> Upgrade to network store v1.18.2

- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
To be consistent with NAD parametters #118 we want to add UndefinedValueSymbol to the generated SLD
> Change symbol of invalid values

- pom.xml
Depends on powsybl/powsybl-ws-dependencies#63
> upgrade to powsybl-ws-dependencies 2.17.0

- src/main/java/com/powsybl/sld/server/NetworkAreaDiagramService.java
> Adapt the NAD scaling with the density of nodes displayed

- src/test/resources/application-default.yml
> Change query log level and update hibernate binder for logging

- src/main/java/com/powsybl/sld/server/NetworkAreaDiagramService.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
- src/main/java/com/powsybl/sld/server/dto/nad/NadConfigInfos.java
- src/main/java/com/powsybl/sld/server/dto/nad/NadGenerationContext.java
- src/main/java/com/powsybl/sld/server/dto/nad/NadRequestInfos.java
- src/main/java/com/powsybl/sld/server/dto/nad/NadVoltageLevelInfos.java
- src/main/java/com/powsybl/sld/server/entities/nad/NadConfigEntity.java
- src/test/java/com/powsybl/sld/server/DiagramConfigRepositoryTest.java
- src/test/java/com/powsybl/sld/server/NetworkAreaDiagramServiceTest.java
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
> Refactor svg generation functions

- pom.xml
- src/main/java/com/powsybl/sld/server/CommonLabelProvider.java
- src/main/java/com/powsybl/sld/server/GridSuiteAndConvergenceComponentLibrary.java
- src/main/java/com/powsybl/sld/server/PositionDiagramLabelProvider.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
- src/main/resources/GridSuiteLibrary/components.json
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
No
Upgrade to powsybl-dependencies 2025.1.0. All changes are linked to this refacto : https://github.com/powsybl/powsybl-diagram/pull/696
> Upgrade to powsybl-dependencies 2025.1.0

- src/main/java/com/powsybl/sld/server/NetworkAreaDiagramService.java
> Fix the generation mode when the nad was already generated.

- src/main/java/com/powsybl/sld/server/NetworkAreaDiagramService.java
- src/main/resources/config/application.yaml
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
If a NAD would be generated with too many voltage levels, a HttpStatus.FORBIDDEN is thrown.
> Limit the number of voltage levels in NAD

- src/main/java/com/powsybl/sld/server/NetworkAreaDiagramService.java
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
> Fix typo in error message

- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
no
chore
unneeded annotation
no more confusion with unneeded annotation
> remove unneeded redundant @ResponseBody annotation in @RestController

- src/main/java/com/powsybl/sld/server/NetworkAreaDiagramService.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramController.java
- src/main/java/com/powsybl/sld/server/SingleLineDiagramService.java
- src/main/java/com/powsybl/sld/server/dto/CurrentLimitViolationInfos.java
- src/main/java/com/powsybl/sld/server/dto/LimitViolationInfos.java
- src/main/java/com/powsybl/sld/server/dto/nad/NadRequestInfos.java
- src/main/java/com/powsybl/sld/server/utils/DiagramUtils.java
- src/main/java/com/powsybl/sld/server/utils/LimitHighlightStyleProvider.java
- src/main/java/com/powsybl/sld/server/utils/TopologicalStyleProvider.java
- src/test/java/com/powsybl/sld/server/SingleLineDiagramTest.java
add support for custom limit violation styles
only equipments with overload (only permanent limit check) are highlighted in SLD and NAD
All diagram generation endpoints have been switched from GET to POST. Applications calling these endpoints will need to update their request method accordingly.
> Add limit violation highlighting support

- pom.xml
> Release v2.24.0
